#ifndef LATITUDERULER_VERSION_H
#define LATITUDERULER_VERSION_H

#define PLUGIN_VERSION_MAJOR 0
#define PLUGIN_VERSION_MINOR 3
#define PLUGIN_VERSION_PATCH 0
#define PLUGIN_VERSION_POST 0

#define OCPN_API_VERSION_MAJOR 1
#define OCPN_API_VERSION_MINOR 18

#endif
